config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  resources :players
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
		def index
			@players = Player.all
		end
	
		def new
			@player = Player.new
		end
	
		def create
			@player = Player.new(player_params)
			if @player.save
				redirect_to players_path
			else
				render :new
			end
		end
	
		def edit
			@player = Player.find(params[:id])
		end
	
		def update
			@player = Player.find(params[:id])
			if @player.update(player_params)
				redirect_to players_path
			else
				render :edit
			end
		end
	
		def destroy
			@player = Player.find(params[:id])
			@player.destroy
			redirect_to players_path
		end
	
		private
	
		def player_params
			params.require(:player).permit(:name, :stats)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CricketTeamManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, 'error') %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :stats %>
    <%= form.text_field :stats %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Edit Player</h1>
<%= render 'form', player: @player %>
<%= link_to 'Back', players_path, class: 'btn btn-secondary' %>

app/views/players/index.html.erb
<h1>Players</h1>
<%= link_to 'New Player', new_player_path, class: 'btn btn-primary' %>
<ul>
  <% @players.each do |player| %>
    <li>
      <%= link_to player.name, edit_player_path(player) %>
      (<%= link_to 'Delete', player_path(player), method: :delete, data: { confirm: 'Are you sure?' } %>)
    </li>
  <% end %>
</ul>

app/views/players/new.html.erb
<h1>New Player</h1>
<%= render 'form', player: @player %>
<%= link_to 'Back', players_path, class: 'btn btn-secondary' %>

<!-- app/views/players/edit.html.erb -->
<h1>Edit Player</h1>
<%= render 'form', player: @player %>
<%= link_to 'Back', players_path, class: 'btn btn-secondary' %>